---

- name: Install apache2 on ubuntu server
  apt: name=apache2 state=present update_cache=yes
  when: ansible_distribution == "Ubuntu"
  notify: restart-apache2

- name: Install httpd on CentOS serer
  yum: name=httpd state=latest
  when: ansible_distribution == "CentOS"
  notify: restart-httpd

